# Generated by Django 4.1.3 on 2023-05-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unisex',
            field=models.BooleanField(default=False),
        ),
    ]
