# Generated by Django 4.1.3 on 2023-05-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_unisex'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.TextField(blank=True),
        ),
    ]
